---
apiVersion: v1
kind: Secret
metadata:
  name: richmond-fnt-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-demo-video/richmond-fnt-gitops